#!/usr/bin/env bash

#SBATCH --job-name="autotest_relax"
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --ntasks=4
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --time=1-00:00:00
#SBATCH --error="j%j.stderr"
#SBATCH --output="j%j.stdout"

hostname > ./hostname
nvidia-smi > ./nvidia-smi
#module load dp/gpu/2.0.1

lmp -i in.lammps -v restart 0
